defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: invoicer
  password: invoicer
  socket: /opt/local/var/run/mysql5/mysqld.sock

development:
  database: invoicer_development
  <<: *defaults

test:
  database: invoicer_test
  <<: *defaults